### ISSUE TITLE
URL of storage on Emails

### ISSUE THREAD

**Issue by platix** [ONLYOFFICE/CommunityServer#12]
Debian server with CommunityServer Versión 8.5.201

When a user received an attached image on an email, the system doesn't show the correct url of the image. For example:
OnlyOffice host: https://my.domain.com
the email has the img src atribute to: http://localhost/addons/mail/data/aggregator/... (IDs and more folders...) ....png

The problem is that it didnt use https://my.domain.com/addons/mail/data/aggregator/... (IDs and more folders...) ....png and use http://localhost...
If I configure DNS Host on settings, it doesn't use the https setting and I can't configure it.

On reset password email, the link is correct.

**Comment by AnaMih** [comment]
The issue has been fixed. Please update the Community Server to apply the bug fix

**Comment by platix** [comment]
Thanks for the fix but the deb package in the ubuntu repository still has the old version.

**Comment by platix** [comment]
Hello,
The bug is still active. Now it's show the machine name for example: 
root@machine:/# hostname
machine

But it doesn't detect if nginx is configure in HTTPS mode.
And if I use the option of custom domain name, I can use https://my.domain.com but it doesn't detect the https (Secure http) URI and when I reload the page, it only show my.domain.com

**Comment by AnaMih** [comment]
Sorry for the inconveniences. We have forwarded the info to our developers and let you know as soon as any solution is found.

**Comment by platix** [comment]
The bug is now fixed, Thanks you
